Add lesson20
ReDI-School/js-berlin-2020-spring pull request #17
Opened 2020-05-17 21:34 UTC by haraldF

2020-05-18 19:24 UTC, sevtapim requested changes

2020-05-18 19:24 UTC, sevtapim commented on lesson20.md
> +      <script>
To prove that we can use the script loaded in header, isn't better to put the code using moment in the body part. To keep the natural flow going and not to wrongly signal that you can only use the scripts loaded in header also in header.

2020-05-18 19:24 UTC, sevtapim commented on lesson20.md
> +let countriesElement = document.getElementById("countries");
Remind that countries is the id we gave to the select HTML element not the variable name we used in the fetchCountries function

2020-05-18 19:24 UTC, sevtapim commented on lesson20.md
> +for (let country of countries) {
Remind here that countries this time referring to the data we fetched in the function

2020-05-18 19:24 UTC, sevtapim commented on lesson20.md
> +    countryElement.value = JSON.stringify(country.latlng);
Explain why we are stringifying the latlng property. Maybe even show the typeof country.latlng before doing the conversion.

2020-05-19 09:20 UTC, carlotrimarchi approved these changes

2020-05-19 15:44 UTC, merged